source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.3"
use_frameworks!

target "TodayNews-Swift" do
    pod 'SnapKit', '~> 3.1.2'
    pod 'Kingfisher', '~>3.3.4'
    pod 'Alamofire', '~> 4.3.0'
    pod 'SwiftyJSON', '~> 3.1.4'
    pod 'IBAnimatable'
end
