# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'HandyJSON'
    pod 'Kingfisher'
    pod 'IBAnimatable'
    pod 'SwiftTheme', :git=>'https://github.com/jiecao-fm/SwiftTheme.git',:branch=>'master'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SQLite.swift'
    pod 'SVProgressHUD'
    pod 'MJRefresh'
    pod 'SGPagingView'
    pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git', :branch => 'master'
    pod 'FDFullscreenPopGesture'
    # pod 'Texture'
    pod 'lottie-ios'
end
