site_name: 头条接口文档

pages:
  - [index.md, 索引]
  - [home.md, 首页]
  - [video.md, 视频]
  - [huoshan.md,  小视频]
  - [mine.md, 我的]
  - [user_detail.md, 用户详情]
  - [dongtai.md, 用户详情动态]
  - [weitoutiao.md, 微头条]
  - [theme.md, 主题颜色]

theme: readthedocs