# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WellsNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WellsNews
   pod 'SwiftLint', '~> 0.26.0'
   pod 'SwiftTheme', :git=>'https://github.com/jiecao-fm/SwiftTheme.git',:branch=>'master'
   pod 'SGPagingView', '~> 1.5.5'
   pod 'Alamofire'
   pod 'SwiftyJSON'
#   pod 'HandyJSON'
 pod '   ', '~> 4.2.0'
   pod 'Kingfisher'
   pod 'IBAnimatable'
   pod 'SwiftTheme', :git=>'https://github.com/jiecao-fm/SwiftTheme.git',:branch=>'master'
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'SQLite.swift'
   pod 'SVProgressHUD'
   pod 'MJRefresh'
   pod 'BMPlayer', :git => 'https://github.com/BrikerMan/BMPlayer.git', :branch => 'master'
   pod 'FDFullscreenPopGesture'

  target 'WellsNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WellsNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
